FROM openjdk:17-alpine AS builder

WORKDIR /app/

COPY ./.mvn/ ./.mvn/
COPY ./mvnw ./
COPY ./pom.xml ./

RUN ./mvnw dependency:go-offline

COPY ./src/ ./src/

RUN ./mvnw clean package -DskipTests

FROM openjdk:17-alpine

WORKDIR /app/

COPY --from=builder /app/target/msvc-gateway-0.0.1-SNAPSHOT.jar ./msvc-gateway.jar


CMD [ "java", "-jar", "msvc-gateway.jar" ]