spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: msvc-auth
              uri: lb://MSVC-AUTH
              predicates:
                - Path=/api/auth/**
            - id: msvc-users
              uri: lb://MSVC-USERS
              predicates:
                - Path=/api/users/**

server:
  port: 8000
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
